//The answer must have balanced parentesis
//HINT: Reuse the code of the former question!
//Complete class Time12 adding add1Hour(), remove1Hour()
//add1Minute(), remove1Minute(), add1Second(), remove1Second()
class Time12 {
  //toString,equals and hashCode as generated by eclipse
  /*omitted*/
  final int seconds;
  final int minutes;
  final int hours;
  final boolean isPm;
  Time12(int seconds, int minutes, int hours,boolean isPm){
    this.seconds=limit60(seconds);
    this.minutes = limit60(minutes);
    this.hours=limitHours(hours);
    this.isPm=isPm;
  }
  private static int limit60(int v){// 0..59 ok
    if(v<0|| v>59){throw new IllegalArgumentException("limit60 over "+v);}
    return v;}
  private static int limitHours(int v){//1..12 ok
    if(v<1|| v>12){throw new IllegalArgumentException("limitHours over "+v);}
    return v;}
  static final Time12 twelve= new Time12(0,0,12,true);

    Time12 temp;
  public Time12 add1Hour(){
    if(this.hours < 12){
    temp = new Time12(this.seconds,this.minutes,this.hours+1,this.isPm);
    }else if (this.hours == 12){
    temp = new Time12(this.seconds,this.minutes,1,!this.isPm);
    }
    return temp;
  }
 

  public Time12 add1Minute(){
    if(this.minutes < 59){
    temp = new Time12(this.seconds,this.minutes+1,this.hours,this.isPm);
    }else if (this.minutes == 59){

            if(this.hours < 12){
            temp = new Time12(this.seconds,0,this.hours+1,this.isPm);
            }else if (this.hours == 12){
            temp = new Time12(this.seconds,0,1,!this.isPm);
            }          

    }
    return temp;
  }

    public Time12 add1Second(){
        if(this.seconds < 59){
        temp = new Time12(this.seconds+1,this.minutes,this.hours,this.isPm);
        }else if (this.seconds == 59){

                  if(this.minutes < 59){
                  temp = new Time12(0,this.minutes+1,this.hours,this.isPm);
                  }else if (this.minutes == 59){

                          if(this.hours < 12){
                          temp = new Time12(0,0,this.hours+1,this.isPm);
                          }else if (this.hours == 12){
                          temp = new Time12(0,0,1,!this.isPm);
                          }          

                  }             

        }
        return temp;
      }





   public Time12 remove1Hour(){
    if(this.hours > 1){
    temp = new Time12(this.seconds,this.minutes,this.hours-1,this.isPm);
    }else if (this.hours == 1 ){
    temp = new Time12(this.seconds,this.minutes,12,!this.isPm);
    }
    return temp;
  }

  public Time12 remove1Minute(){
    if(this.minutes > 0){
    temp = new Time12(this.seconds,this.minutes-1,this.hours,this.isPm);
    }else if (this.minutes == 0 ){

            if(this.hours > 1){
            temp = new Time12(this.seconds,59,this.hours-1,this.isPm);
            }else if (this.hours == 1 ){
            temp = new Time12(this.seconds,59,12,!this.isPm);
            }                       

    }
    return temp;
  }

   
  public Time12 remove1Second(){
    if(this.seconds > 0){
    temp = new Time12(this.seconds-1,this.minutes,this.hours,this.isPm);
    }else if (this.seconds == 0 ){
      
            if(this.minutes > 0){
            temp = new Time12(59,this.minutes-1,this.hours,this.isPm);
            }else if (this.minutes == 0 ){

                    if(this.hours > 1){
                    temp = new Time12(59,59,this.hours-1,this.isPm);
                    }else if (this.hours == 1 ){
                    temp = new Time12(59,59,12,!this.isPm);
                    }                       

            }              


    }
    return temp;
  }

  }
  public class Exercise{
    /*omitted*/
  }
  public static void main(String[]arg){
    /*omitted*/
  }
}
